name = "iwate-event-navigator"
compatibility_date = "2024-08-16"
pages_build_output_dir = "dist"

[[headers]]
for = "*.js"
  [headers.values]
  "Content-Type" = "application/javascript; charset=utf-8"
  "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.js"
  [headers.values]
  "Content-Type" = "application/javascript; charset=utf-8"
  "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.mjs"
  [headers.values]
  "Content-Type" = "application/javascript; charset=utf-8"
  "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "/"
  [headers.values]
  "Content-Type" = "text/html; charset=utf-8"
  "X-Content-Type-Options" = "nosniff"
  "X-Frame-Options" = "DENY"
  "X-XSS-Protection" = "1; mode=block"
  "Referrer-Policy" = "strict-origin-when-cross-origin"