name = "iwate-event-navigator"
compatibility_date = "2024-08-16"

[env.production]
# Build configuration
[env.production.build]
command = "npm run build"
cwd = ""

# Static site configuration
[env.production.site]
bucket = "dist"