# Iwate Event Navigator Hybrid ETL Source Configuration
# Following the redesign documents in docs/event-collection-redesign/
# Schema validation: docs/event-collection-redesign/sources.schema.yaml

version: "1.0.0"
description: "Primary sources for Iwate event collection - RSS/ICS/API priority"
lastUpdated: "2025-08-31"

# PRIORITY 1: RSS/ICS/API SOURCES (Primary data collection)
government:
  - id: iwate_news_rss
    name: "岩手県公式ニュースRSS" 
    url: "https://www.pref.iwate.jp/news.rss"
    type: rss_feed
    category: general
    region: all
    reliability: 1.0
    updateFrequency: daily
    enabled: true
    notes: "Primary government source - highest priority"

  - id: morioka_event_calendar
    name: "盛岡市イベントカレンダー"
    url: "https://www.city.morioka.iwate.jp/event_calendar.html"
    type: html_scraping
    category: general
    region: kenou
    reliability: 0.9
    updateFrequency: daily
    enabled: true
    selectors:
      list: ".event-list li, .calendar-event, .news-item, article"
      title: "h3, h4, .title, .event-title, a"
      url: "a@href"
      date: ".date, .time, time, .event-date"
      venue: ".venue, .place, .location"
    fetchConfig:
      parseRules:
        containerSelector: ".event-list li, .calendar-event, .news-item, article, .content-section"
        titleSelector: "h3, h4, .title, .event-title, a"
        descriptionSelector: ".description, .content, p"
        dateSelector: ".date, .time, time, .event-date"
        locationSelector: ".venue, .place, .location"
    notes: "盛岡市公式イベント一覧（市公式ドメイン）"

  - id: morioka_festival_event
    name: "盛岡市 まつり・イベント"
    url: "https://www.city.morioka.iwate.jp/kankou/kankou/1037105/index.html"
    type: html_scraping
    category: festivals
    region: kenou
    reliability: 0.9
    updateFrequency: weekly
    enabled: true
    notes: "盛岡市公式 観光系イベント（市公式ドメイン）"

# Community API sources (Connpass, Doorkeeper)
community:
  - id: connpass_iwate
    name: "Connpass 岩手"
    url: "https://connpass.com/api/v1/event/"
    type: api
    category: community
    region: all
    reliability: 0.95
    updateFrequency: daily
    enabled: true
    mapping:
      title: "events[].title"
      starts_at: "events[].started_at"
      ends_at: "events[].ended_at"
      url: "events[].event_url"
      venue: "events[].address"
      organizer: "events[].owner_display_name"
    keywords: ["盛岡"]
    
  - id: doorkeeper_iwate
    name: "Doorkeeper 岩手"
    url: "https://api.doorkeeper.jp/events"
    type: api
    category: community
    region: all
    reliability: 0.9
    updateFrequency: daily
    enabled: true
    keywords: ["盛岡"]

# PRIORITY 2: Well-structured HTML sources
tourism:
  - id: iwate_kenmin_hall
    name: "岩手県民会館"
    url: "https://www.iwate-kenmin.jp/events/"
    type: html_scraping
    category: cultural
    region: kenou
    reliability: 0.85
    updateFrequency: weekly
    enabled: true
    selectors:
      list: ".event-item"
      title: ".event-title"
      url: ".event-link@href"
      date: ".event-date"
      venue: ".event-venue"
    notes: "Well-structured site with consistent markup"

  - id: iwate_tabi
    name: "いわての旅"
    url: "https://iwatetabi.jp/events/"
    type: html_scraping
    category: cultural
    region: all
    reliability: 0.8
    updateFrequency: weekly
    enabled: false
    notes: "Official tourism portal - good structured data"

  - id: odette_morioka
    name: "盛岡観光情報（イベントカレンダー）"
    url: "https://www.odette.or.jp/?page_id=264"
    type: html_scraping
    category: cultural
    region: kenou
    reliability: 0.85
    updateFrequency: weekly
    enabled: true
    notes: "盛岡観光コンベンション協会のイベント情報"

# PRIORITY 3: Secondary sources (disabled by default for PoC)
regional:
  kenou:
    - id: hanamaki_kanko
      name: "花巻市観光協会"
      url: "https://www.kanko-hanamaki.ne.jp/event/"
      type: html_scraping
      category: cultural
      region: kenou
      reliability: 0.75
      updateFrequency: weekly
      enabled: false  # Disabled for PoC - enable only if primary sources insufficient
      notes: "Secondary source - enable only if needed"

# Processing configuration (following redesign specs)
processing:
  deduplication:
    titleSimilarityThreshold: 0.8
    dateSimilarityThresholdMs: 14400000  # 4 hours
    locationSimilarityThreshold: 0.7
    enableFuzzyMatching: true
  caching:
    defaultTTL: 3600000  # 1 hour
    maxCacheSize: 1000
  rateLimiting:
    maxConcurrentRequests: 1
    requestDelayMs: 1000  # 1 second between requests
  validation:
    requireTitle: true
    requireDate: true
    requireLocation: false  # Allow events without specific location
    futureEventsOnly: true
    maxEventAge: 31536000000  # 1 year in milliseconds

# Quality gates (following redesign KPIs)
quality:
  minimumEventsPerSource: 1
  maximumFailureRate: 0.02  # 2% max failure rate
  minimumReliabilityScore: 0.7
